### PR TITLE
use "makedirs" instead of "mkdir"

### LINKED ISSUE #85: use "makedirs" instead of "mkdir"
Hi,

creating a survey with `setup_tex` inside a multi-level subfolder fails currently. This patch remedies the problem:

```patch
diff --git a/sdaps/setupodt/__init__.py b/sdaps/setupodt/__init__.py
index 75e0dbb..7156a25 100644
--- a/sdaps/setupodt/__init__.py
+++ b/sdaps/setupodt/__init__.py
@@ -132,7 +132,7 @@ def setup(survey, questionnaire_odt, questionnaire_pdf, additionalqobjects, opti
     print unicode(survey.questionnaire)
 
     # Create the survey
-    os.mkdir(survey.path())
+    os.makedirs(survey.path())
 
     log.logfile.open(survey.path('log'))
 
diff --git a/sdaps/setuptex/__init__.py b/sdaps/setuptex/__init__.py
index 79a0133..f9ceab4 100644
--- a/sdaps/setuptex/__init__.py
+++ b/sdaps/setuptex/__init__.py
@@ -83,7 +83,7 @@ def setup(survey, questionnaire_tex, additionalqobjects=None, extra_files=[]):
     survey.add_questionnaire(model.questionnaire.Questionnaire())
 
     # Create the survey directory, and copy the tex file.
-    os.mkdir(survey.path())
+    os.makedirs(survey.path())
     try:
         shutil.copy(questionnaire_tex, survey.path('questionnaire.tex'))
 
```

works for me... ;-)

### PR DESCRIPTION
**Pull request by marvin2k**
meh, forking for two lines of change

closes #85

Signed-off-by: Martin Zenzes <martin.zenzes@dfki.de>

### CODE REVIEW

**Comment by benzea** [comment]
Yeah, but it does simply things for me.

**Comment by marvin2k** [comment]
Sure, for you it's easier this way ,-) Thanks for the software. Great piece!

**Comment by marvin2k** [comment]
Now that we are talking: there is still one `os.mkdir` in [sdaps/utils/image.py](https://github.com/sdaps/sdaps/blob/master/sdaps/utils/image.py#L68) but the comment says

> Create directory if it does not exists. Assumes only one level is missing.

so I didn't change it.

**Comment by benzea** [comment]
Wouldn't have hurt, but right now it does not make a difference. This is always a subdirectory of an already existing directory right now.

**Pull request merged**
